services:
  bot:
    build: .
    command: python bot.py
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import os; print(1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
