services:
  sprint-bot:
    build: .
    env_file:
      - .env
    ports:
      - "8443:8443"
    volumes:
      - sprint-bot-data:/app/data
      - sprint-bot-logs:/app/logs
    environment:
      BOT_TOKEN: ${BOT_TOKEN:?BOT_TOKEN must be set}
    restart: unless-stopped

volumes:
  sprint-bot-data:
  sprint-bot-logs:
