"""Callback data constants for main menu interactions."""

CB_MENU_ADD_RESULT = "menu:add_result"
CB_MENU_TEMPLATES = "menu:templates"
CB_MENU_REPORTS = "menu:reports"
CB_MENU_PROGRESS = "menu:progress"
CB_MENU_LEADERBOARD = "menu:leaderboard"
CB_MENU_SETTINGS = "menu:settings"
CB_MENU_HISTORY = "menu:history"
CB_MENU_STAYER = "menu:stayer"
CB_MENU_RECORDS = "menu:records"
CB_MENU_MESSAGES = "menu:messages"
CB_MENU_INVITE = "menu:invite"
CB_MENU_ADMIN = "menu:admin"
CB_MENU_NOOP = "menu:noop"
CB_MENU_QUICK_ADD_RESULT = "menu:quick_add_result"
CB_MENU_TODAY_TRAINING = "menu:today_training"
CB_MENU_MY_RECENT_PRS = "menu:recent_prs"
CB_MENU_TEAM_SUMMARY = "menu:team_summary"
