name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy pytest pytest-cov ruff

      - name: Run Ruff
        run: ruff check .

      - name: Run mypy
        run: mypy services utils

      - name: Run pytest with coverage
        run: pytest --cov=services --cov=utils --cov-report=term-missing --cov-fail-under=60

      - name: Run turn analytics tests
        run: pytest tests/test_turn_service.py tests/test_turn_analytics.py -q
